// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WorkoutJournal.Data.Enum;

namespace WorkoutJournal.Data.Models;

public partial class Workouts
{
    public int WorkoutID { get; set; }

    public int WorkoutTypeID { get; set; }

    public int SessionID { get; set; }

    public PerceivedExertion? PerceivedExertionKind { get; set; }

    public int Repetitions { get; set; }

    public decimal Weight { get; set; }

    public virtual WorkoutSessions Session { get; set; }

    public virtual WorkoutTypes WorkoutType { get; set; }
}