// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WorkoutJournal.Data.Models;

public partial class WorkoutJournalContext : DbContext
{
    public WorkoutJournalContext(DbContextOptions<WorkoutJournalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<WorkoutSessions> WorkoutSessions { get; set; }

    public virtual DbSet<WorkoutTypes> WorkoutTypes { get; set; }

    public virtual DbSet<Workouts> Workouts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WorkoutSessions>(entity =>
        {
            entity.HasKey(e => e.SessionID).HasName("PK__WorkoutS__C9F49270F5A77AA6");

            entity.Property(e => e.SessionDate).HasColumnType("date");
        });

        modelBuilder.Entity<WorkoutTypes>(entity =>
        {
            entity.HasKey(e => e.WorkoutTypeID).HasName("PK__WorkoutT__DF2CC05E241540E9");

            entity.Property(e => e.ExerciseName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Workouts>(entity =>
        {
            entity.HasKey(e => e.WorkoutID).HasName("PK__Workouts__E1C42A2141D31013");

            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Session).WithMany(p => p.Workouts)
                .HasForeignKey(d => d.SessionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Workouts__Sessio__628FA481");

            entity.HasOne(d => d.WorkoutType).WithMany(p => p.Workouts)
                .HasForeignKey(d => d.WorkoutTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Workouts__Workou__619B8048");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}